/root/venv/lib/python3.12/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@AAPvhWvmVEUgTEC v5.5.3 (immunity)
--- ***** ----- 
-- ******* ---- Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.39 2025-06-14 05:17:33
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         celery_app:0x7418044f84d0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 20 (solo)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . tasks.run_task

[2025-06-14 05:17:33,075: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 2.00 seconds... (1/100)

[2025-06-14 05:17:35,078: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 4.00 seconds... (2/100)

[2025-06-14 05:17:39,079: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 6.00 seconds... (3/100)

[2025-06-14 05:17:45,080: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 8.00 seconds... (4/100)

[2025-06-14 05:17:53,083: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 10.00 seconds... (5/100)

[2025-06-14 05:18:03,084: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 12.00 seconds... (6/100)

[2025-06-14 05:18:15,131: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 14.00 seconds... (7/100)

[2025-06-14 05:18:29,172: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 16.00 seconds... (8/100)

[2025-06-14 05:18:45,175: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 18.00 seconds... (9/100)

[2025-06-14 05:19:03,248: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 20.00 seconds... (10/100)

[2025-06-14 05:19:23,390: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 22.00 seconds... (11/100)

[2025-06-14 05:19:45,411: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 24.00 seconds... (12/100)

[2025-06-14 05:20:09,472: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 26.00 seconds... (13/100)

[2025-06-14 05:20:35,498: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 28.00 seconds... (14/100)

[2025-06-14 05:21:03,580: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 30.00 seconds... (15/100)

[2025-06-14 05:21:33,651: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:22:05,729: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:22:37,796: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:23:09,874: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:23:41,903: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:24:13,938: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:24:45,973: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:25:18,004: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:25:50,032: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:26:22,056: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:26:54,079: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:27:26,099: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:27:58,116: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:28:30,130: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:29:02,141: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:29:34,179: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:30:06,245: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:30:38,292: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:31:10,348: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:31:42,412: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:32:14,436: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:32:46,478: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:33:18,516: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:33:50,528: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:34:22,538: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:34:54,565: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:35:26,574: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:35:58,582: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:36:30,614: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:37:02,635: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:37:34,651: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:38:06,669: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:38:38,697: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:39:10,732: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:39:42,760: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:40:14,797: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:40:46,835: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:41:18,887: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:41:50,909: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:42:22,948: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:42:54,982: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:43:27,022: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:43:59,051: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:44:31,067: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:45:03,095: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:45:35,152: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:46:07,166: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:46:39,182: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:47:11,199: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:47:43,232: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:48:15,253: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:48:47,277: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:49:19,292: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:49:51,305: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:50:23,319: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:50:55,332: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:51:27,378: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:51:59,447: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:52:31,492: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:53:03,552: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:53:35,614: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:54:07,651: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:54:39,683: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:55:11,718: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:55:43,751: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:56:15,802: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:56:47,841: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:57:19,874: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:57:51,910: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:58:23,951: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:58:56,006: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 05:59:28,064: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:00:00,122: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:00:32,160: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:01:04,233: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:01:36,297: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:02:08,344: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:02:40,365: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:03:12,413: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:03:44,468: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:04:16,521: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:04:48,562: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:05:20,570: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:05:52,580: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:06:24,591: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 1 connecting to localhost:6379. Operation not permitted..
Trying again in 32.00 seconds... (16/100)

[2025-06-14 06:06:56,604: CRITICAL/MainProcess] Unrecoverable error: OperationalError('Error 1 connecting to localhost:6379. Operation not permitted.')
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
           ^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 769, in _connect
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 938, in _connection_factory
    self._connection = self._establish_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel
    channel = self.Channel(connection)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/transport/redis.py", line 751, in __init__
    self.client.ping()
  File "/root/venv/lib/python3.12/site-packages/redis/commands/core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 1530, in get_connection
    connection.connect()
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "/root/venv/lib/python3.12/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 1 connecting to localhost:6379. Operation not permitted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/root/venv/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/venv/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 341, in start
    blueprint.start(self)
  File "/root/venv/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/venv/lib/python3.12/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
                   ^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 472, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 478, in connection_for_read
    return self.ensure_connected(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 530, in ensure_connected
    conn = conn.ensure_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 406, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/root/venv/lib/python3.12/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 1 connecting to localhost:6379. Operation not permitted.
